[gray-scott]
# Parameters of the simulation
grid_size = 128
t_step = 1.0
t_show = 50
solver = "euler"
# Parameters of the model equations
du = 0.16
dv = 0.08
f = 0.060
k = 0.062
stencil = 5

[kuramoto]
num_oscillators = 50
coupling_strength = 1.0
t_step = 0.1
t_show = 0.1
distribution = "normal"
solver = "rk"
