[fitzhugh-nagumo]
# Parameters of the simulation
t_end = 100
num_points = 1000
v0 = 0
w0 = 0
limits = [-3, -3, 3, 3]
param_name = "i_ext"
param_limits = [0, 2]
# Parameters of the model equations
i_ext = 0.5
a = 0.7
b = 0.8
tau = 12.5
r = 0.1

[morris-lecar]
# Parameters of the simulation
t_end = 200
num_points = 1000
v0 = -60.0
w0 = 0.0
limits = [-60.0, 0.0, 80.0, 1.0]
param_name = "i_ext"
param_limits = [0, 100]
# Parameters of the model equations
i_ext = 40.0
c = 20.0
g_ca = 4.0
g_k = 8.0
g_l = 2.0
v_ca = 120.0
v_k = -84.0
v_l = -60.0
v1 = -1.2
v2 = 18.0
v3 = 2.0
v4 = 30.0
phi = 0.04

[gray-scott]
# Parameters of the simulation
grid_size = 128
speed = 1
# Parameters of the model equations
du = 0.16
dv = 0.08
f = 0.060
k = 0.062
dt = 1.0
stencil = 5

[kuramoto]
num_oscillators = 1
coupling_strength = 1.0
dt = 0.1
distribution = "normal"
