[fitzhugh-nagumo]
v0 = 0
w0 = 0
limits = [-3, -3, 3, 3]
i_ext = 0.5
a = 0.7
b = 0.8
tau = 12.5
r = 0.1
param_name = "i_ext"
param_limits = [0, 2]

[morris-lecar]
v0 = -60.0
w0 = 0.0
limits = [-60.0, 0.0, 80.0, 1.0]
i_ext = 40.0
c = 20.0
g_ca = 4.0
g_k = 8.0
g_l = 2.0
v_ca = 120.0
v_k = -84.0
v_l = -60.0
v1 = -1.2
v2 = 18.0
v3 = 2.0
v4 = 30.0
phi = 0.04
param_name = "i_ext"
param_limits = [0, 100]