import matplotlib.pyplot as plt
import numpy as np


def lorenz(
    xyz: np.ndarray,
    *,
    s: float = 10.0,
    r: float = 28.0,
    b: float = 8.0 / 3.0,
) -> np.ndarray:
    """Evaluate the Lorenz vector field at a point in phase space.

    Parameters
    ----------
    xyz : np.ndarray
       Point in three-dimensional phase space with shape ``(3,)``.
    s, r, b : float
       Parameters defining the Lorenz system.

    Returns
    -------
    np.ndarray
       Time derivative evaluated at ``xyz``.
    """
    x, y, z = np.asarray(xyz, dtype=float)
    x_dot = s * (y - x)
    y_dot = r * x - y - x * z
    z_dot = x * y - b * z
    return np.array([x_dot, y_dot, z_dot], dtype=float)


def simulate_lorenz(
    initial_state: tuple[float, float, float] = (0.0, 1.0, 1.05),
    dt: float = 0.01,
    num_steps: int = 10000,
    *,
    s: float = 10.0,
    r: float = 28.0,
    b: float = 8.0 / 3.0,
) -> np.ndarray:
    """Simulate the Lorenz system with forward Euler time stepping.

    Parameters
    ----------
    initial_state : tuple[float, float, float], optional
       Initial condition for the trajectory.
    dt : float, optional
       Time step for the numerical integration.
    num_steps : int, optional
       Number of Euler steps to integrate.
    s, r, b : float
       Parameters defining the Lorenz system.

    Returns
    -------
    np.ndarray
       Trajectory array with shape ``(num_steps + 1, 3)``.
    """
    if dt <= 0:
        raise ValueError("dt must be positive")
    if num_steps < 1:
        raise ValueError("num_steps must be at least 1")

    trajectory = np.empty((num_steps + 1, 3), dtype=float)
    trajectory[0] = np.asarray(initial_state, dtype=float)

    for step_index in range(num_steps):
        trajectory[step_index + 1] = trajectory[step_index] + (
            lorenz(trajectory[step_index], s=s, r=r, b=b) * dt
        )

    return trajectory


def trajectory_separation(
    trajectory_a: np.ndarray, trajectory_b: np.ndarray
) -> np.ndarray:
    """Compute the pointwise Euclidean distance between two trajectories.

    Parameters
    ----------
    trajectory_a, trajectory_b : np.ndarray
       Trajectory arrays with matching shape ``(n, 3)``.

    Returns
    -------
    np.ndarray
       Euclidean separation at each time step.
    """
    if trajectory_a.shape != trajectory_b.shape:
        raise ValueError("trajectory_a and trajectory_b must have the same shape")

    return np.linalg.norm(trajectory_a - trajectory_b, axis=1)


def main(
    initial_state: tuple[float, float, float] = (0.0, 1.0, 1.05),
    dt: float = 0.01,
    num_steps: int = 10000,
    *,
    s: float = 10.0,
    r: float = 28.0,
    b: float = 8.0 / 3.0,
) -> None:
    """Plot a Lorenz trajectory generated by forward Euler integration.

    Parameters
    ----------
    initial_state : tuple[float, float, float], optional
       Initial condition for the trajectory.
    dt : float, optional
       Time step for the numerical integration.
    num_steps : int, optional
       Number of time steps to integrate.
    s, r, b : float
       Parameters defining the Lorenz system.
    """
    trajectory = simulate_lorenz(
        initial_state=initial_state,
        dt=dt,
        num_steps=num_steps,
        s=s,
        r=r,
        b=b,
    )

    fig = plt.figure(figsize=(8, 5))
    ax = fig.add_subplot(projection="3d")

    ax.plot(*trajectory.T, lw=0.6)
    ax.set_xlabel("X Axis")
    ax.set_ylabel("Y Axis")
    ax.set_zlabel("Z Axis")
    ax.set_title("Lorenz Attractor")

    plt.show()


if __name__ == "__main__":
    main()
