## Exercise: OpenFlights Network

This repository contains several example network datasets. Among these is a network of US air travel routes:

```{python}
G = nx.read_graphml("./data/openflights/openflights_usa.graphml.gz")

print(G)
print("Nodes:", G.nodes())

pos = nx.circular_layout(G)
nx.draw(G, pos=pos, node_size=10)
plt.show()
```

The nodes in this graph are airports, represented by their [IATA codes](https://en.wikipedia.org/wiki/List_of_airports_by_IATA_code:_A); two nodes are connected with an edge if there is a scheduled flight directly connecting these two airports. We'll assume this graph to be undirected since a flight in one direction usually means there is a return flight.

Thus this graph has edges

```
[('HOM', 'ANC'), ('BGM', 'PHL'), ('BGM', 'IAD'), ...]
```

where ANC is Anchorage, IAD is Washington Dulles, etc.

These nodes also have **attributes** associated with them, containing additional information about the airports, in the form of a dictionary:

```{python}
G.nodes["IND"]
```

**Exercise.** Is there a direct flight between Indianapolis and Fairbanks, Alaska (FAI)? A direct flight is one with no intermediate stops.

```{python}
# Your code here
```

**Exercise.** If I wanted to fly from Indianapolis (IND) to Fairbanks, Alaska (FAI) what would be an itinerary with the fewest number of flights?

```{python}
# Your code here
```

**Exercise.** Is it possible to travel from any airport in the US to any other airport in the US, possibly using connecting flights? In other words, does there exist a path in the network between every possible pair of airports (is the graph connected)?

```{python}
# Your code here
```

**Exercise.** Which airports are the most important for connectivity?

```{python}
# Your code here
```

**Exercise.** What happens if a major hub is removed?

```{python}
# Your code here
```