---
title: "Assignment"
subtitle: "Couzin Model"
format: html
---

Simulate the Couzin model and report your findings.

You can follow the guide here:

[Couzin Model](couzin.qmd){.btn .btn-primary}

## Option A: Couzin Model

1. Implement the Couzin rules and motion.
2. Implement an animation that shows the individuals moving. You can see an example in the [Vicsek animation](vicsek-animation.qmd){.btn .btn-primary} chapter.
3. Implement an order parameter that quantifies the degree of alignment in the system. Read the original paper [@couzin2002collective] to find out how they defined it. You can also check the [Vicsek order parameter](vicsek.qmd#order-parameter) for inspiration.
4. Explore the parameter space and report your insights. Find the four collective dynamical behaviours described in the original paper [@couzin2002collective].

Upload the code and a short report (1-2 pages done in LaTeX) describing your findings to the course platform.

### Extra Mile (Optional)

- Add sliders to allow change parameters (of your choice) on real time.
- Implement the model in 3D, following the original paper [@couzin2002collective].

## Option B: Vicsek Model with Predator Avoidance

We can take the avoidance rule from the Couzin model and add it to the Vicsek model. But instead of a repulsion from other particles, we will have a repulsion from a predator. The predator can be a fixed point in space or a moving point that follows its own dynamics (e.g. random walk). Or even better, we can make the predator be our mouse cursor!

If you want to go for this option, you can follow the guide here:

[Vicsek with Predator Avoidance](vicsek-predator.qmd){.btn .btn-primary}

Your goal is:

1. Implement the full Vicsek animation as shown in the [Vicsek animation](vicsek-animation.qmd){.btn .btn-primary} chapter.
2. Implement the predator avoidance rule and add a predator to the animation.
3. Explore the parameter space and report your insights. How does the predator affect the collective behaviour of the particles? Can you find a regime where the particles can escape the predator?

Upload the code and a short report (1-2 pages done in LaTeX) describing your findings to the course platform.

\vspace{1cm}

**Good luck and enjoy your coding!**
